{"name": "test_CredKart_Login_params_003[data_for_login3]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <TestCases.test_Login_params.Test_CredKart_Login_params object at 0x00000238943D9F50>\nsetup = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"5d19d2c4-61bb-4b78-a522-b6ea67a9dbf0\")>\ndata_for_login = ('Credencetst@test.com', 'Credence@126')\n\n    def test_CredKart_Login_params_003(self, setup, data_for_login):\n        self.driver = setup\n        self.driver.get(\"https://automation.credence.in/login\")\n        self.driver.find_element(By.XPATH, \"//input[@name='email']\").send_keys(data_for_login[0])\n        self.driver.find_element(By.CSS_SELECTOR, \"input[id='password']\").send_keys(data_for_login[1])\n        self.driver.find_element(By.XPATH, \"//button[@type='submit']\").click()\n        try:\n>           self.driver.find_element(By.XPATH, \"//h2[normalize-space()='CredKart']\")\n\nTestCases\\test_Login_params.py:13: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nC:\\Users\\nomul\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:739: in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\nC:\\Users\\nomul\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:345: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x0000023894398410>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"no such element\",\"message\":\"Unable to locate element: //h2[normalize-spac.../content/shared/webdriver/Errors.sys.mjs:505:5\\\\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:132:16\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //h2[normalize-space()='CredKart']; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:187:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:505:5\nE       dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:132:16\n\nC:\\Users\\nomul\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py:229: NoSuchElementException\n\nDuring handling of the above exception, another exception occurred:\n\nself = <TestCases.test_Login_params.Test_CredKart_Login_params object at 0x00000238943D9F50>\nsetup = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"5d19d2c4-61bb-4b78-a522-b6ea67a9dbf0\")>\ndata_for_login = ('Credencetst@test.com', 'Credence@126')\n\n    def test_CredKart_Login_params_003(self, setup, data_for_login):\n        self.driver = setup\n        self.driver.get(\"https://automation.credence.in/login\")\n        self.driver.find_element(By.XPATH, \"//input[@name='email']\").send_keys(data_for_login[0])\n        self.driver.find_element(By.CSS_SELECTOR, \"input[id='password']\").send_keys(data_for_login[1])\n        self.driver.find_element(By.XPATH, \"//button[@type='submit']\").click()\n        try:\n            self.driver.find_element(By.XPATH, \"//h2[normalize-space()='CredKart']\")\n            self.driver.save_screenshot(\".\\\\Screenshots\\\\\" + data_for_login[0] + \"_\" + data_for_login[1] + \"_\" + \"test_CredKart_Login_002_Pass.PNG\")\n            print('Login TestCase is Passed')\n            self.driver.close()\n            assert True\n        except:\n            print('Login TestCase is Failed')\n            self.driver.save_screenshot(\".\\\\Screenshots\\\\\" + data_for_login[0] + \"_\" + data_for_login[1] + \"_\" + \"test_CredKart_Login_002_fail.PNG\")\n            self.driver.close()\n>           assert False\nE           assert False\n\nTestCases\\test_Login_params.py:22: AssertionError"}, "parameters": [{"name": "data_for_login", "value": "('Credencetst@test.com', 'Credence@126')"}], "start": 1691821002981, "stop": 1691821036548, "uuid": "053cff43-a7bd-4709-8181-836f56686b2d", "historyId": "d6514f178bec2c6188645a746759aeba", "testCaseId": "7db63bd431a82a92cb21f75d1263e1c0", "fullName": "TestCases.test_Login_params.Test_CredKart_Login_params#test_CredKart_Login_params_003", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_Login_params"}, {"name": "subSuite", "value": "Test_CredKart_Login_params"}, {"name": "host", "value": "LAPTOP-1DT8TVKR"}, {"name": "thread", "value": "19624-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_Login_params"}]}